"""
University of Liege
ELEN0062 - Introduction to machine learning
Project 1 - Classification algorithms
"""
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
from matplotlib import pyplot as plt

from data import make_dataset1, make_dataset2
from sklearn.neighbors import KNeighborsClassifier


# (Question 2)

# Put your funtions here
# ...


if __name__ == "__main__":
    pass # Make your experiments here

    # observe how model complexity impacts the classification boundary.
    # To do so, we will build several nearest neighbor models with n_neighbors values of 
    # 1,
    # 5,
    # 25,
    # 125,
    # 625,
    # 1200

    # For this question, you should work on datasets generated by make_dataset2.
    # Answer the following questions in your report.
    # 1. Observe how the decision boundary is affected by the number of neighbors:

    # (a) illustrate the decision boundary for each value of n_neighbors.
    # (b) comment on the evolution of the decision boundary with respect to the number of neighbors.

    # 2. Report the average test set accuracies over five generations of the dataset, 
    # along with the standard deviations, for each value of n_neighbors. Briefly
    # comment on them.
